### PR TITLE
By yanniboi: Updated composer drush version to 9.

### PR DESCRIPTION
**Pull request by yanniboi**
Trying to fix the composer dependency jumble with drupal 8 dev (8.4.x-dev) which seems to now be liking the drush version...

### CODE REVIEW

**Comment by yanniboi** [comment]
hmmm... no that's still failing

**Comment by yanniboi** [comment]
Ok, so I've found the problems... Drupal 8.4.x now uses symfony/yaml v3.2.6. Drush 8 does not support this, but we can upgrade to using an alpha release of drush 9 which will support the new version of yaml.

More of an issue is that drupal console does not support symfony/http-foundation v3.2.6 (also a requirement of drupal 8.4.x), not even the latest dev. So drupal-project will currently now build with drupal console.

What would you prefer? Not support latest dev or not require console?

**Comment by webflo** [comment]
The template is designed to work with 8.3.x atm. I think should remove drupal/console for 8.4.x tests and drop PHP 5.5 because its not compatible with Drush 9. Take a look at the test failures in https://github.com/drupal-composer/drupal-project/pull/270

**Comment by yanniboi** [comment]
I am closing this as a duplicate of #270

**Pull request closed without merging**
