### PR TITLE
#502: Add php extensions requirements

### PR DESCRIPTION
**Pull request by cybtachyon**
https://github.com/drupal-composer/drupal-project/issues/502

### CODE REVIEW

**Comment by joestewart** [comment]
That is a different list of extensions than core uses. I'm curious.

https://git.drupalcode.org/project/drupal/blob/8.8.x/core/composer.json#L7-19 and https://github.com/drupal/core/blob/8.8.x/composer.json#L7-L20

**Comment by cybtachyon** [comment]
Good point! I've updated it to be closer to core composer.json as well as https://www.drupal.org/docs/8/system-requirements/php-requirements

Thanks!

**Comment by andypost** [comment]
Btw it looks better as patch to core itself

**Comment by AlexSkrypnyk** [comment]
There is no need to specify these in the project `composer.json` as they are inherited from core.

**Pull request closed without merging**
