### PR TITLE
Store site configuration outside of the docroot

### PR DESCRIPTION
**Pull request by webflo**
Lets add the <code>$config_directories</code> by default. The installer creates the directory automatically. Its not not required to create it in the script handler itself.

### CODE REVIEW

**Comment by webflo** [comment]
<code>webmozart/path-util</code> is already a drush dependency. But i will add it as a root dependency.

**Comment by webflo** [comment]
I realised its possible to get rid of ScriptHandler::getDrupalRoot

**Comment by pfrenssen** [comment]
Looking good to me. Code looks good and I also tried it out and it works beautifully!

**Comment by webflo** [comment]
Thanks! For the review, rebased and committed to 8.x

**Pull request closed without merging**
