### PR TITLE
Use composer-patches

### PR DESCRIPTION
**Pull request by jcnventura**
Following the documentation work done in #73, I'm proposing to add cweagans/composer-patches to the required packages in composer.json, and to document how to use it in the README.md.

I'm pretty sure this package will be used by everyone as long as we have the current patch workflow in drupal.org.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Great idea: +1

**Comment by webflo** [comment]
Yes it is a good idea. Can you squash both commits together? Thanks

**Comment by jcnventura** [comment]
Squashed as requested.

**Comment by webflo** [comment]
Thanks!

**Pull request merged**
