### PR TITLE
using drupal.org official repositories

### PR DESCRIPTION
**Pull request by madalinignisca**
I've altered the skeleton to use the drupal.org repository. For me it worked well.

### CODE REVIEW

**Comment by webflo** [comment]
Hi @madalinignisca, would you like to maintain the D7 branch?

**Comment by madalinignisca** [comment]
Hi @webflo , yes of course. It's an honour to do that.

**Comment by webflo** [comment]
Added you as a maintainer.

**Comment by madalinignisca** [comment]
I have grants only on 8.x branch. Shouldn't I have on 7.x?

**Comment by webflo** [comment]
Fixed it. Go ahead

**Comment by derimagia** [comment]
Any update on this? Did you need some assistance with this?

**Comment by madalinignisca** [comment]
Hi @webflo , I have no permissions on the 7.x, or the 8.x that I had initial. Can you check please?

**Comment by webflo** [comment]
@madalinignisca  Sorry, should work now.

**Pull request merged**
