### PR TITLE
Add lando config

### PR DESCRIPTION
**Pull request by geekygnr**
I thought it would be helpful if the repo had a very basic lando configuration. I would encourage similar done for all common tools for quick dev environment setup.

### CODE REVIEW

**Comment by normanlolx** [comment]
👍 Nice to have, yes. But environment is totally up to every developer themself and goes beyond the scope of this template I guess.

**Comment by truls1502** [comment]
> 👍 Nice to have, yes. But environment is totally up to every developer themself and goes beyond the scope of this template I guess.

I am totally agreed with you, @leymannx that it should be up to every developer.
However, I believe it would be nice to have some popular recipes for development environments such as [DDEV](https://ddev.readthedocs.io) and [Lando](https://docs.devwithlando.io) to let the new beginner try to spin up the Drupal site in just a few secs. It could save a lot of their time, especially first time so they can play more with Drupal then later they can customise after their need. For the advanced developers so we can create a patch with our own customised on these development environments.

**Comment by geekygnr** [comment]
@truls1502 Thank you. I think you put my thought process down in a far more elegant way than I ever could.

**Comment by AlexSkrypnyk** [comment]
@truls1502 Currently, most of the code in the repo is covered with tests. How would you check that what you are proposing is working in CI? 

I think this project is not a place for development environment configurations.

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!

**Pull request closed without merging**
