### PR TITLE
move drush commands folder outside webroot

### PR DESCRIPTION
**Pull request by yched**
PR for https://github.com/drupal-composer/drupal-project/issues/20

### CODE REVIEW

**Comment by weitzman** [comment]
Actually we can keep the three subdirs and the README file now that Drush merged drush-ops/drush#1480

**Comment by webflo** [comment]
Cool, https://github.com/drush-ops/drush/issues/1664 got it.

@yched Can you re-roll the patch and move drush to the repo root instead deleting it?

**Comment by yched** [comment]
Like that ?

Also, should we recommend a separation of drush/commands/ into contrib/ & custom/, like we do for modules and themes ?
i.e. have `"drush/commands/contrib/{$name}": ["type:drupal-drush"]` in installer-paths ?

**Comment by weitzman** [comment]
:+1: 

I think that separation is unnecessary. A project will have far fewer contrib commandfiles than contrib modules.

**Comment by yched** [comment]
Sure, but the custom ones will be in a folder that is committed in the
project repo, while the contrib ones will be in a folder that is
composer-pulled & git-ignored ? So I'd think two folders still make sense
regardless of the # of projects in each ?

**Comment by weitzman** [comment]
then the two folders should be 'local' and 'exernal'?

**Comment by yched** [comment]
well, the "installer-path" already puts contrib modules & themes in
module/contrib & themes/contrib, not sure why we introduce a different
pattern here ?

**Comment by weitzman** [comment]
I guess I dont have any real world experience here yet. I'll defer to you
guys.

**Comment by webflo** [comment]
I think we should go with `"drush/contrib/{$name}": ["type:drupal-drush"]` for contrib and remove the three existing folders because most projects don´t need it? We could extend the README we some relevant links to documentation instead.

**Comment by helderco** [comment]
I agree with @webflo on `"drush/contrib/{$name}"`.

**Comment by yched** [comment]
I like having less folders in drush/ :-)

Where would a project put the things that were intended for drush/config and drush/site-aliases then ?

**Comment by webflo** [comment]
@yched directly in `/drush`

**Comment by yched** [comment]
Works for me. Will update the PR later today

**Comment by yched** [comment]
done

**Comment by webflo** [comment]
Thanks!: :+1:

**Comment by yched** [comment]
Yay !

**Comment by webflo** [comment]
Doh! The PR was incomplete. Fixed it with faac08e93b7bcdc74d660ec6b16a901f25755b4c

**Comment by yched** [comment]
Er. Oops, sorry about that :-(

**Comment by helderco** [comment]
Is this enough? drush isn't picking up my drush/drushrc.php.

```
$ composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction
$ cd some-dir
$ echo '<?php $options["shell-aliases"]["devel"] = "en -y devel";' > drush/drushrc.php
$ drush status
[no root, no config]
$ drush -r $PWD/web status
[with root, no config]
$ cd web
$ drush status
[with root, no config]
```

**Comment by weitzman** [comment]
Put drushrc.php in the drush/ folder. It will get picked up anytime you specify --root ,or anytime your cwd is under web/

**Comment by helderco** [comment]
@weitzman If you look at my commands above, I'm doing exactly that. Not working.

**Comment by weitzman** [comment]
I can confirm that it isn't working. Maybe we added this for aliases only. In any case, this is a drush bug that I will fix this week.

**Comment by helderco** [comment]
Yeah, I commented on drush-ops/drush#1379. Thanks.

**Comment by weitzman** [comment]
Fixed by https://github.com/drush-ops/drush/commit/8a3620ee1e65bab7eb8069d57606db74148b8e64

**Pull request merged**
