### PR TITLE
Add drupal/console by default

### PR DESCRIPTION
**Pull request by webflo**

### CODE REVIEW

**Comment by webflo** [comment]
@jmolivas Which version constraint should we use?

**Comment by jmolivas** [comment]
@webflo: I think `"drupal/console": "~0.8",` is fine for now.

Please ping me when this gets merged and it's ready to test.

**Comment by webflo** [comment]
Alright

**Comment by jmolivas** [comment]
@webflo: New drupal/console tag released https://github.com/hechoendrupal/DrupalConsole/releases/tag/0.8.3

**Comment by webflo** [comment]
Jup, works like a charm, Thanks!

**Pull request merged**
