### PR TITLE
Use packages.drupal.org repository

### PR DESCRIPTION
**Pull request by webflo**

### CODE REVIEW

**Comment by pfrenssen** [comment]
Can you please provide some more background information about this change? This breaks all my dependencies. If I visit https://packages.drupal.org/8 I see no information about some kind of official Drupal package repository.

**Comment by pfrenssen** [comment]
https://github.com/drupal-composer/drupal-project/pull/159

**Comment by webflo** [comment]
Drupal.org provides all package information you need. You can run `composer info --all drupal/devel`` for example to see all available versions. https://packages.drupal.org/8 does not provide a web-frontend atm.

**Comment by webflo** [comment]
You have to use the new version numbers (remove the 8/7 at the beginning). See https://www.drupal.org/node/2718229 for more information.

**Comment by pfrenssen** [comment]
It's awesome :heart_eyes: - now we also need a frontend for packages.drupal.org!

**Pull request merged**
