### PR TITLE
Copy the editor config and gitattributes from drupal to the root.

### PR DESCRIPTION
**Pull request by rodrigoaguilera**

### CODE REVIEW

**Comment by weitzman** [comment]
Seems reasonable to me. I dont know whats up with the tests. I'm gonna rerun them.

**Comment by webflo** [comment]
I try to fix the tests in https://github.com/drupal-composer/drupal-project/pull/405. I made some good progress on PHP 5.6 but struggle with symfony deprecation helper in tests.

**Comment by webflo** [comment]
👍

**Comment by webflo** [comment]
Thanks!

**Comment by rodrigoaguilera** [comment]
Thank you for such a great effort on maintaining this project 😃

I think this is also useful to show that drupal-scaffold can also be configured.

**Pull request merged**
