### PR TITLE
Can't install because no matching package found

### PR DESCRIPTION
**Pull request by Unifex**
I had the semi-regular composer issue in the title and found issue #511 was current and had the solution.  It looked like there wasn't a pull request for it though.  This should resolve that.  

Credit should go to @jamie-tillman.

### CODE REVIEW

**Comment by normanlolx** [comment]
This is just a temporary fix. And this issue shouldn't be fixed here but in https://github.com/webflo/drupal-core-require-dev/pull/13.

**Comment by rodrigoaguilera** [comment]
To clarify: the webflo repo only copies what is in drupal core so the problem so it should be fixed one step upstream

https://www.drupal.org/project/drupal/issues/3078671

**Comment by normanlolx** [comment]
+1 for upstream. Thanks for clarifying!

**Comment by Unifex** [comment]
Fair call.  If nothing has happened upstream by tomorrow I'll take a look at that.  It's the end of my day here.

**Pull request closed without merging**
