### PR TITLE
Update to drupal-composer/drupal-scaffold ^2. 

### PR DESCRIPTION
**Pull request by greg-1-anderson**
buildScaffold script is no longer necessary.

See https://github.com/drupal-composer/drupal-scaffold/pull/38

### CODE REVIEW

**Comment by RobLoach** [comment]
:+1:

**Comment by greg-1-anderson** [comment]
Failures look spurious; going to re-run the failing tests and see if they pass.

**Comment by webflo** [comment]
@greg-1-anderson I am already on it. We have to convert the 8.1.x-dev to 8.1.x. Thats the branch name

**Comment by greg-1-anderson** [comment]
@webflo: There was one "could not download from GitHub" failure; I re-ran it, and then saw the error you mention above.  Thanks for looking at that.

**Comment by webflo** [comment]
Alright, i had to fix the tests first https://github.com/drupal-composer/drupal-scaffold/pull/41

**Comment by webflo** [comment]
Lets continue in https://github.com/drupal-composer/drupal-project/pull/154

**Pull request closed without merging**
