### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by webflo**

### CODE REVIEW

**Comment by yched** [comment]
Why do we add things like mikey179/vfsStream, phpunit/phpunit ? aren't they require-dev provided by in drupal/core ?

**Comment by jibran** [comment]
Yes all the required-dev can go away.

**Comment by webflo** [comment]
`require-dev` is root-only config directive. https://getcomposer.org/doc/04-schema.md#require-dev

Its means we have to add these dependencies to your root composer.json

**Comment by webflo** [comment]
Maybe we should provide them as a meta-package, but this fixes the tests until we have a better solution.

**Comment by yched** [comment]
Aw. Thanks, didn't know that :-)

**Pull request merged**
