### PR TITLE
Redirect root to /web

### PR DESCRIPTION
**Pull request by mathieutu**
Add a .htaccess in the root folder to be redirected if you visit directly this folder.

Thx for your work.

### CODE REVIEW

**Comment by mathieutu** [comment]
Some news about that ?

**Comment by derhasi** [comment]
@mathieutu can you explain why you need this?
This project is intended to only have the web folder being accessible via the web.

**Comment by mathieutu** [comment]
In my case it's for development, I replaced standard drupal sources by yours, but I'm still using the drupal docker container. It permit me to be directly redirected on web without any special config.

As you want, it's just in case, because it can be useful for some people.

**Comment by worthwhileindustries** [comment]
Seems like kind of a unique situation. I'm not sure why you wouldn't just configure the docroot to be web?

**Comment by webflo** [comment]
Its not a sane default for this project imo. https://github.com/wodby/docker4drupal has great docker containers and docroot ist configurable via a environment variable.

**Comment by mathieutu** [comment]
Ok, no problem.
Thx!

**Pull request closed without merging**
