### PR TITLE
Add macOS "DS_Store" invisible files to .gitignore

### PR DESCRIPTION
**Pull request by mazleo**

### CODE REVIEW

**Comment by normanlolx** [comment]
I think you should better ignore them from your own global ignore file. This Composer template is a starter template you then can adjust to match your needs or match your OS.

**Comment by jcnventura** [comment]
We start with macOS .DS_Store, then eventually all other IDE files get added.

This is a path we should not take.

**Comment by AlexSkrypnyk** [comment]
@mazleo 

These kinds of files should never be added to projects and should be excluded locally.

 please see https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by webflo** [comment]
I agree with @leymannx @jcnventura and @alexdesignworks. Please configure your global gitignore :)

Thanks all!

**Pull request closed without merging**
